require("monarch.plugins.telescope")
require("monarch.plugins.which-key")
require("monarch.plugins.lsp.mason")
require("monarch.plugins.lsp.lsp")
require("monarch.plugins.flutter-tools")
require("monarch.plugins.nvim-cmp")
require("monarch.plugins.dap")
